# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd1b70fa618ababcbe9bc997afbf85ecee998d127c5f2081c8e693368c5db1c5671e2442a3594f6e430a8c8ab08151f4f1ee3b74b3a4628e8b0999384c4d0bd2

test:
  secret_key_base: 3862f1839454f01f5597209c35f2c89067cf5d008a5811e1393b5f87ae27c73d5191488ee735cc0eeeb3cc90e846fb63086f65b290771b721f0cec3a80bc43bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
